# Logger Configurations
# "level" defines the log level
# available options
#  - ERROR (default)
#  - DEBUG
#  - INFO
#  - WARN
level: "ERROR"
remote_log: true
file_path_enabled: true

# "colors" define whether logging colors will be enabled or not
colors: true

# "targets" define logging targets
# available options
console: true
file: false

# "directory" defines the directory to be used for logging
# will use "logs" directory in the project root directory as default
directory: "logs"